version: "2"

checks:
  # Many of these are disabled, simply because we have performance tradeoffs
  # as opposed to simply refactoring calls into separate functions. There are
  # places strategically where doing this can cause noticeable slowdown.
  # The same applies to cognitive complexity unfortunately. File line counts
  # are also ignored as some parts of Discord's API have many endpoints we have
  # to cover, and splitting this into separate components would make it less
  # intuitive to the end user.
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

exclude_patterns:
  - "**.png"
  - "tests/**"
  - "test/**"
  - "scripts/**"
  - "pipelines/**"
  - "pages/**"
  - "docs/**"
  - ".run/**"
  - ".github/**"
