stages:
  - test
  - pages

cache:
    key: ${CI_JOB_NAME}
    paths:
      - .venv/
      - .cache/

variables:
  DOCKER_DRIVER: "overlay2"
  PACKAGE: "hikari"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cpython3.6:
  stage: test
  image: python:3.6-alpine
  before_script:
    - python -V
    - apk add git
    - pip install tox
    - tox -avv
  script:
    - tox
    - tox -e formatcheck
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

cpython3.7:
  stage: test
  image: python:3.7-alpine
  before_script:
    - python -V
    - apk add git
    - pip install tox
    - tox -avv
  script:
    - tox
    - tox -e formatcheck
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

cpython3.8:
  stage: test
  image: python:3.8-rc-alpine
  before_script:
    - python -V
    - apk add git
    - pip install tox
    - tox -avv
  script:
    - tox
    - tox -e formatcheck
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

pypy3.6:
  stage: test
  image: pypy:3.6-slim
  before_script:
    - pypy3 -V
    - apt-get update
    - apt-get install git -y
    - pip install tox
    - tox -avv
  script:
    - tox
    # Black fails on PyPy, I don't care that much.
    # BUG: https://bitbucket.org/pypy/pypy/issues/2985/pypy36-osreplace-pathlike-typeerror
    # - tox -e formatcheck
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

pages:
  stage: pages
  image: python:3-stretch
  before_script:
    # - apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk  -y
    - pip install tox
  script:
    - tox -e docs
    - cd public && mv html/* .
    # - cd latex
    # - latexmk
  only:
    - master
  except:
    - schedules
  artifacts:
    paths:
      - public
      - public/latex
