stages:
  - test
  - verify
  - pages

variables:
  DOCKER_DRIVER: "overlay2"
  PACKAGE: "hikari"

cpython3.6:
  stage: test
  image: python:3.6-alpine
  before_script:
    - python -V
    - apk add git
    - pip install tox
    - tox -avv
  script:
    - tox
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

cpython3.7:
  stage: test
  image: python:3.7-alpine
  before_script:
    - python -V
    - apk add git
    - pip install tox
    - tox -avv
  script:
    - tox
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

cpython3.8:
  stage: test
  image: python:3.8-rc-alpine
  before_script:
    - python -V
    - apk add git
    - pip install tox
    - tox -avv
  script:
    - tox
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

pypy3.6:
  stage: test
  image: pypy:3.6-slim
  before_script:
    - pypy3 -V
    - apt-get update
    - apt-get install git -y
    - pip install tox
    - tox -avv
  script:
    - tox
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/

.pages:
  image: python:3-stretch
  before_script:
    # - apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk  -y
    - pip install tox
  script:
    - tox -e docs
    - cd public && mv html/* .
    # - cd latex
    # - latexmk
  artifacts:
    paths:
      - public
      - public/latex

pages:
  stage: pages
  extends: .pages
  only:
    - master
  except:
    - schedules


pages-test:
  stage: pages
  extends: .pages
  except:
    - master

black:
  stage: verify
  allow_failure: true
  image: python:3-alpine
  before_script:
    - pip install tox 
  script:
    - tox -e formatcheck
  except:
    - master
