stages:
  - test
  - pages

cache:
    key: ${CI_JOB_NAME}
    paths:
      - .venv/
      - .cache/

variables:
  DOCKER_DRIVER: "overlay2"
  PACKAGE: "hikari"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

.base:
  image: python:3.7-alpine
  before_script:
    - apk add --no-cache --update python3-dev gcc build-base
    - pip install -r requirements.txt -r test-requirements.txt

test-3.7:
  extends: .base
  stage: test
  script:
    - python pipelines.py tests
  coverage: /^TOTAL[\s\d%]+\s(\d+\%)$/
  artifacts:
    paths:
      - public/coverage

test-3.8:
  extends: test-3.7
  image: python:3.8-rc-alpine

sast:
  extends: .base
  stage: test
  script:
    - python pipelines.py sast

black:
  extends: .base
  stage: test
  allow_failure: true
  script:
    - python pipelines.py black --check

.pages:
  extends: .base
  script:
    - python pipelines.py docs

pages:
  stage: pages
  extends: .pages
  after_script:
    - mv docs/build/html/* public/ -v
  artifacts:
    paths:
      - public
  only:
    - master

test-pages:
  stage: test
  extends: .pages
  after_script:
    - mkdir public -v || true
    - mkdir public/test-pages -v || true
    - mv docs/build/html/* public/test-pages -v
  artifacts:
    paths:
      - public
  except:
    - master
