# Copyright © Nekoka.tt 2019-2020
#
# This file is part of Hikari.
#
# Hikari is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hikari is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Hikari. If not, see <https://www.gnu.org/licenses/>.

stages:
  - test
  - verify
  - deploy
  - post-deploy

variables:
  DOCKER_DRIVER: "overlay2"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SAST_BANDIT_EXCLUDED_PATHS: tests/*,docs/*,gitlab/*,insomnia/*,public/*,tasks/*,noxfile.py
  SAST_EXCLUDED_PATHS: tests/*,docs/*,gitlab/*,insomnia/*,public/*,tasks/*,noxfile.py

include:
  - local: "/gitlab/test.yml"
  - local: "/gitlab/analysis.yml"
  - local: "/gitlab/pages.yml"
  - local: "/gitlab/deploy.yml"
  - template: "Dependency-Scanning.gitlab-ci.yml"
  - template: "SAST.gitlab-ci.yml"
  - template: "License-Management.gitlab-ci.yml"
  
license_scanning:
  # Overly slow currently, so only run on staging and master.
  only:
    - master
    - staging
