stages:
  - test
  - pages

cache:
    key: ${CI_JOB_NAME}
    paths:
      - .venv
      - .cache/pip

variables:
  DOCKER_DRIVER: overlay2
  PIPENV_INSTALL: "pipenv install --skip-lock"
  PIPENV_VENV_IN_PROJECT: "yes"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

.base:
  image: python:3.7-alpine
  before_script:
    - apk add --no-cache --update python3-dev gcc build-base
    - python -m pip install pipenv
    - ${PIPENV_INSTALL} --dev
    - export VENV_HOME_DIR=$(pipenv --venv)
    - source $VENV_HOME_DIR/bin/activate
    - pipenv graph

test-3.7:
  extends: .base
  stage: test
  script:
    - nosetests --rednose --force-color -c nose.cfg
  coverage: &cov '/TOTAL:\s+\d+\%/'
  artifacts:
    paths:
      - public/coverage

test-3.8:
  extends: test-3.7
  image: python:3.8-rc-alpine

sast:
  extends: .base
  stage: test
  script:
    - ${PIPENV_INSTALL} bandit
    - bandit -r hikari -n 3

.pages:
  extends: .base
  script:
    - python docs/generate_rst.py . hikari docs/source docs/source/index.rst
    - cd docs
    - make clean html
    - cd ..
    - mkdir public/test-pages -v

pages:
  stage: pages
  extends: .pages
  after_script:
    - mv docs/build/html/* public/ -v
  artifacts:
    paths:
      - public
  only:
    - master

test-pages:
  stage: test
  extends: .pages
  after_script:
    - mv docs/build/html/* public/test-pages -v
  artifacts:
    paths:
      - public
  except:
    - master
