stages:
  - test
  - pages

cache:
    key: ${CI_JOB_NAME}
    paths:
      - .venv/
      - .cache/

variables:
  DOCKER_DRIVER: "overlay2"
  PACKAGE: "hikari"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

.base:
  image: python:3.7-alpine
  before_script:
    - apk add --no-cache --update python3-dev gcc build-base
    - pip install -r requirements.txt -r test-requirements.txt

test-3.7:
  extends: .base
  stage: test
  script:
    - >
      pytest -l -v --color=yes \
                   --cov-report term-missing \
                   --cov-report annotate:public/coverage-src \
                   --cov-report html:public/coverage \
                   --cov-branch \
                   --cov=${PACKAGE} tests/

  coverage: '/TOTAL:\s+\d+\%/'
  artifacts:
    paths:
      - public/coverage

test-3.8:
  extends: test-3.7
  image: python:3.8-rc-alpine

sast:
  extends: .base
  stage: test
  script:
    - pip install bandit
    - bandit -r ${PACKAGE} -n 3

black:
  extends: .base
  stage: test
  allow_failure: true
  script:
    - pip install black
    - python -m black ${PACKAGE} --verbose --py36 --check

.pages:
  extends: .base
  script:
    - pip install sphinx sphinx-autodoc-typehints sphinxcontrib-asyncio sphinx_bootstrap_theme
    - python docs/generate_rst.py . ${PACKAGE} docs/source docs/source/index.rst
    - cd docs
    - make clean html
    - cd ..

pages:
  stage: pages
  extends: .pages
  after_script:
    - mv docs/build/html/* public/ -v
  artifacts:
    paths:
      - public
  only:
    - master

test-pages:
  stage: test
  extends: .pages
  after_script:
    - mkdir public -v || true
    - mkdir public/test-pages -v || true
    - mv docs/build/html/* public/test-pages -v
  artifacts:
    paths:
      - public
  except:
    - master
