stages:
  - test
  - sast

variables:
  PIPENV_INSTALL: "pipenv install --skip-lock"

.base:
  image: python:3.7-alpine
  before_script:
    - apk add --no-cache --update python3-dev  gcc build-base
    - python -m pip install pipenv
    - ${PIPENV_INSTALL} --dev
    - export VENV_HOME_DIR=$(pipenv --venv)
    - source $VENV_HOME_DIR/bin/activate
    - pipenv graph
    # Fire up the venv
  cache:
    key: ${CI_JOB_NAME}

Test:
  extends: .base
  stage: test
  script:
    - nosetests --rednose --force-color -c nose.cfg
  coverage: &cov '/TOTAL:\s+\d+\%/'
  artifacts:
    paths:
      - public/coverage

Test-3.8:
  extends: Test
  image: python:3.8-rc-alpine

SAST:
  extends: .base
  stage: sast
  script:
    - ${PIPENV_INSTALL} bandit
    - bandit -r nekokattpy -n 3
