version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

python:
   install:
     - requirements: dev-requirements.txt

search:
  ignore:
    # Defaults
    - search.html
    - search/index.html
    - 404.html
    - 404/index.html

    # Custom
    - index.html
    - changelog/index.html
