version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    # NOTE: This should be kept up to date with ci.yml
    python: "3.13"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --frozen --only-group nox
    - .venv/bin/nox -s mkdocs
