version: 2

build:
  os: ubuntu-22.04
  tools:
    # NOTE: This should be kept up to date with ci.yml
    python: "3.11"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r dev-requirements.txt
    - .venv/bin/nox -s mkdocs
