version: "3"

services:
  test-client:
    entrypoint: bash -c 'pip install --pre hikari && python -m hikari.clients.test --shards=2'
    env_file:
      - credentials.env
    image: python:3.8
    restart: always
