#!/bin/bash

# Put this in .git/hooks to make sure 'black' runs every time you commit.

if [[ -z ${SKIP_HOOK} ]]; then
    command -v nox || pip install nox
    echo -e '\e[1;32mRUNNING HOOKS - prepend your invocation of git commit with SKIP_HOOK=1 to skip this.\e[0m'
    nox -s check-formatting || nox -s reformat-code | grep -oP '^reformatted \K.*' | xargs -d'\n' -I '{}' git add -n '{}'
    nox --sessions pytest pylint pydocstyle
else
    echo -e '\e[1;31mSKIPPING COMMIT HOOKS. THIS IS HERESY!\e[0m'
fi
