version: "3.7"
services:
  py36:
    build:
      context: ../..
      dockerfile: .ci/local-test-runners/cpython3.6.dockerfile
    entrypoint: python -bbBm pytest hikari_tests
    volumes:
      - ../../hikari:/hikari:ro
      - ../../hikari_tests:/hikari_tests:ro
    restart: 'no'

  py37:
    build:
      context: ../..
      dockerfile: .ci/local-test-runners/cpython3.7.dockerfile
    entrypoint: python -bbBm pytest hikari_tests
    volumes:
      - ../../hikari:/hikari:ro
      - ../../hikari_tests:/hikari_tests:ro
    restart: 'no'

  py38:
    build:
      context: ../..
      dockerfile: .ci/local-test-runners/cpython3.8.dockerfile
    entrypoint: python -bbBm pytest hikari_tests
    volumes:
      - ../../hikari:/hikari:ro
      - ../../hikari_tests:/hikari_tests:ro
    restart: 'no'

  py39:
    build:
      context: ../..
      dockerfile: .ci/local-test-runners/cpython3.9.dockerfile
    # entrypoint: python -bbBm pytest hikari_tests
    volumes:
      - ../../hikari:/hikari:ro
      - ../../hikari_tests:/hikari_tests:ro
    restart: 'no'

  pypy3:
    build:
      context: ../..
      dockerfile: .ci/local-test-runners/pypy3.6.dockerfile
    entrypoint: pypy3 -bbBm pytest hikari_tests
    volumes:
      - ../../hikari:/hikari:ro
      - ../../hikari_tests:/hikari_tests:ro
    restart: 'no'

volumes:
  hikari:
  hikari_tests:
