// Copyright (c) 2020 Nekokatt
// Copyright (c) 2021 davfsa
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Prebuilds the indexes for faster loading times.
//
// First argument must be the `index.js` file generated by pdoc.
// Second argument is the path to place the prebuilt index to.

const lunr = require('lunr');
const fs = require('fs');

const args = process.argv.slice(2);
const data = require('./' + '../'.repeat(args[0].split("/").length - 2) + args[0]);

// i: id
// r: ref
// n: name
// d: doc
var idx = lunr(function () {
    this.ref('i');
    this.field('r', { boost: 10 });
    this.field('n', { boost: 5 });
    this.field('d');
    this.metadataWhitelist = ['position'];
    data.index.forEach((doc, i) => {
        const parts = doc.r.split('.');
        doc['n'] = parts[parts.length - 1];
        doc['i'] = i;
        this.add(doc);
    }, this);
});

fs.writeFile(args[1], JSON.stringify(idx), function (err) {
    if (err) { throw err; };
    console.log('Prebuilt index saved to ' + args[1]);
});
