# Copyright © Nekoka.tt 2019
#
# This file is part of Hikari.
#
# Hikari is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hikari is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Hikari. If not, see <https://www.gnu.org/licenses/>.

.deploy:
    allow_failure: false
    stage: deploy
    image: python:3-stretch
    before_script:
        - source tasks/config.sh
        - "[[ \"$CI_PROJECT_URL\" = \"$ORIGINAL_REPO_URL\" ]] || (echo 'You are running off of a fork, so deployment is skipped.' && exit 0)"
        - apt-get update
        - apt-get install curl git openssh-client -y
        - "git log -1 --pretty=%B | grep -iq '\[skip deploy\]' && (echo 'Deployment was skipped by commit message.' && exit 0)"
        - pip install poetry requests
        - poetry install -v
        - poetry show -v

deploy-to-staging:
    extends: .deploy
    only:
        - staging
    except:
        - tags
        - merge_requests
        - schedules
    variables:
        RELEASE_WEBHOOK_NAME: "pypi (prerelease only)"
        RELEASE_WEBHOOK_COLOUR: "0xd34615"
    script:
        - export RELEASE_WEBHOOK_DESCRIPTION=''
        - source tasks/deploy.sh
        - do-deployment
    environment:
        name:
            staging

deploy-to-prod:
    extends: .deploy
    only:
        - master
    except:
        - tags
        - merge_requests
        - schedules
    variables:
        RELEASE_WEBHOOK_NAME: "pypi"
        RELEASE_WEBHOOK_COLOUR: "0x5c2040"
    script:
        - export RELEASE_WEBHOOK_DESCRIPTION=''
        - source tasks/deploy.sh
        - do-deployment
    environment:
        name:
            prod
