# Copyright © Nekoka.tt 2019
#
# This file is part of Hikari.
#
# Hikari is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hikari is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Hikari. If not, see <https://www.gnu.org/licenses/>.

###
### TEMPLATE FOR TEST AND PROD DOCUMENTATION GENERATION JOBS.
###
.pages:
  allow_failure: false
  image: python:3.8.0
  before_script:
    - rm public -Rvf || true
    - mkdir public || true
    - bash tasks/retry-aborts.sh pip install virtualenv
    - pip install virtualenv
    - python -m venv .venv
    - source .venv/bin/activate
    - bash tasks/retry-aborts.sh pip install -U pip
    - bash tasks/retry-aborts.sh pip install poetry
    - bash tasks/retry-aborts.sh poetry update
    - source tasks/config.sh
    - git fetch --all --prune --depth=1

pages:
  stage: pages
  extends: .pages
  script:
    - source tasks/deploy.sh
    - git fetch --all --prune

    - git checkout origin/staging -f || true
    - git status || true

    - set-versions "$(python tasks/make-version-string.py staging pages)" || true

    # Staging should work always.
    - nox -r -sdocumentation

    - mv public staging || true
    - mkdir public || true
    - mv staging public/staging
    
    - set-versions "$(python tasks/make-version-string.py master pages)" || true

    # Check out the master hikari source code.
    - git checkout origin/master -- hikari/
    - nox -r -sdocumentation
  artifacts:
    paths:
      - public
  only:
    - staging
