# Copyright © Nekoka.tt 2019
#
# This file is part of Hikari.
#
# Hikari is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hikari is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Hikari. If not, see <https://www.gnu.org/licenses/>.

###
### TEMPLATE FOR TEST AND PROD DOCUMENTATION GENERATION JOBS.
###
.pages:
  allow_failure: false
  image: python:3.8.0
  before_script:
    - rm public -Rvf || true
    - mkdir public || true
    - apt-get update -q  # graphviz won't resovle without this???
    - apt-get install -qy git gcc g++ make graphviz
    - pip install virtualenv
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip
    - pip install poetry
    - poetry update
    - source tasks/config.sh
    - git fetch --all --prune --depth=1

pages:
  stage: pages
  extends: .pages
  script:
    - source tasks/deploy.sh
    - git fetch --all --prune

    - git checkout origin/staging -f || true
    - git status || true

    - set-versions "$(python tasks/make-version-string.py staging)" || true

    # If staging is messed up, just ignore it...
    - nox -r -sdocumentation || true

    - mv public staging || true
    - mkdir public || true
    - mv staging public/staging

    - git reset --hard origin/staging
    - git checkout origin/master -f
    - git status
    
    - nox -r -sdocumentation
  artifacts:
    paths:
      - public
  only:
    - staging
