# Copyright © Nekoka.tt 2019
#
# This file is part of Hikari.
#
# Hikari is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hikari is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Hikari. If not, see <https://www.gnu.org/licenses/>.

.test:
    only:
        - branches
        - merge_requests
        - tags
        - schedules
    cache:
        paths:
            - $CI_PROJECT_DIR/.pytest_cache
            - $CI_PROJECT_DIR/.nox
            - $CI_PROJECT_DIR/.venv
            - $CI_PROJECT_DIR/.cache/pip
            - $CI_PROJECT_DIR/poetry.lock
        key: $CI_COMMIT_REF_SLUG-$CI_JOB_STAGE-$CI_JOB_NAME
        policy: pull-push
    allow_failure: false
    stage: test
    before_script:
        - apt-get install -qy git gcc g++ make
        - pip install virtualenv
        - >
            if [[ "${CI_IS_SCHEDULED}" -eq "1" ]] || [[ ! -f .venv ]]; then
                echo -e "\e[0;35mInstalling new venv and installing poetry inside it.\e[0m"
                rm poetry.lock .cache/pip .venv/ .nox/ .pytest_cache/ -Rf || true
                python -m venv .venv
                source .venv/bin/activate
                pip install -U pip
                pip install poetry
                poetry update
            else
                echo -e "\e[0;36mReusing cached venv from GitLab caches.\e[0m"
                source .venv/bin/activate
            fi
        - source tasks/config.sh
        - python -V
        - mkdir public || true
        - poetry show -v
    script:
        - nox --sessions pytest bandit stats --report public/nox.json
        - nox --sessions black -- --check
    artifacts:
        paths:
            - public/coverage/
            - public/nox.json
    coverage: /^TOTAL[\s\d%]+\s(\d+(?:\.\d+)?\%)$/

unittest-py37:
    image: python:3.7.5
    extends: .test

unittest-py38:
    image: python:3.8.0
    extends: .test

test-pip-install:
    image: python:3.8.0
    extends: .test
    stage: test
    script:
        - nox --sessions install

verify-pypi-release:
    image: python:3.8.0
    extends: .test
    stage: verify
    script:
        - nox --sessions install -- --showtime
    only:
        - master